title: Leonardo Bertolazzi
logo:  # you can add own logo.
description:
baseurl: ""
url: https://leobertolazzi.github.io # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Leonardo Bertolazzi
  image: '/assets/img/about.jpeg'
  job: Ciao, I'm Leonardo!
  bio: |+
    <br />
    I'm a master's student in Cognitive Science at <a href="https://www.cimec.unitn.it/en">CIMeC</a>, University of Trento, Italy. My research interests lie at the intersection of Cognitive Science and AI, with a focus on evaluation methods for AI systems, multimodality, and conversational AI.
    <br />
    <br />
    If you have any questions about my research or if you're interested in collaborating, please feel free to get in touch!
    <br />
  email: leonardo.bertolazzi@studenti.unitn.it
  github: https://github.com/leobertolazzi
  last_update:  September 2023
  twitter: https://twitter.com/leo_bertolazzi
  linkedin: https://www.linkedin.com/in/leonardo-bertolazzi

# Contact links
# TODO: Potentially add later.
#contact:
#   - name: Twitter
#     link: https://twitter.com/leo_bertolazzi
#

# Comment Section (Disqus)
disqus-identifier: sho-personal # add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics:
# add your identifier. For example UA-99631805-1.

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
